blank_issues_enabled: false
contact_links:
  - name: Deep Cove Education Trust
    url: https://deepcovehostel.co.nz/contact-us
    about: You can contact the Deep Cove Education Trust via their website or email office@deepcovehostel.co.nz
